apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-deployment
  labels:
    app: sample-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample-service
          image: localhost:5000/sample-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-entrypoint
spec:
  type: NodePort
  selector:
    app: sample-service
  ports:
    - port: 3000
      targetPort: 8080
